#define PSC_CASE_LABEL "mirror_bikappa3"
#define PSC_DISTRIBUTION_LABEL "Bi-Kappa"
#define PSC_OUTPUT_BASENAME "prt_mirror_bikappa3"

#define PSC_USE_KAPPA 1
#define PSC_KAPPA 3.0

#define PSC_NMAX_DEFAULT 1200000
#define PSC_CHECKPOINT_EVERY_DEFAULT 5000
#define PSC_STATS_EVERY 50

#define PSC_MASS_RATIO 200.
#define PSC_LAMBDA0 20.
#define PSC_VA_OVER_C 0.05
#define PSC_BETA_E_PAR 1.0
#define PSC_BETA_I_PAR 5.0
#define PSC_TI_PERP_OVER_TI_PAR 3.0
#define PSC_TE_PERP_OVER_TE_PAR 1.0

#define PSC_DOMAIN_DI 20.0
#define PSC_NGRID_DEFAULT 1024
#define PSC_NP_Y_DEFAULT 64
#define PSC_NP_Z_DEFAULT 16
#define PSC_NICELL_DEFAULT 1500

#define PSC_BALANCE_INTERVAL 2500
#define PSC_FIELDS_EVERY_DEFAULT 500
#define PSC_PARTICLES_EVERY_DEFAULT 10000
#define PSC_COLLISION_TEMP g.Te_perp

#include "psc_anisotropy_case.hxx"
